# Generated by Django 4.2.16 on 2026-06-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_alter_fieldclosure_field_alter_fieldschedule_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldswap',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('searching', 'Đang tìm sân thay thế'), ('proposed', 'Đã đề xuất'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('failed', 'Không thể đổi')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Thấp - Có thể tiếp tục chơi'), ('medium', 'Trung bình - Nên đổi sân'), ('high', 'Cao - Buộc phải dừng chơi')], default='medium', max_length=10, verbose_name='Mức độ nghiêm trọng'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('investigating', 'Đang điều tra'), ('resolving', 'Đang giải quyết'), ('resolved', 'Đã giải quyết'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Còn mở?'),
        ),
    ]
