# Generated by Django 4.2.16 on 2026-06-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_id_alter_bookingserviceitem_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingserviceitem',
            options={'ordering': ['id'], 'verbose_name': 'Mục dịch vụ booking', 'verbose_name_plural': 'Mục dịch vụ booking'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Chờ thanh toán cập'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending_payment', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
