# Generated by Django 4.2.16 on 2026-06-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchrequest_accepted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchrequesttimeslot',
            options={'verbose_name': 'Khung giờ giao luu', 'verbose_name_plural': 'Khung giờ giao luu'},
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giữ chỗ đến'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('waiting_opponent', 'Chờ đối chấp nhận'), ('accepted_waiting_deposit', 'Đã có đối chấp nhận, chờ thanh toán cọc'), ('deposit_paid', 'Đã thanh toán cọc'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy')], default='waiting_opponent', max_length=40, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='matchrequesttimeslot',
            name='match_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_timeslots', to='matches.matchrequest', verbose_name='Yeu cau giao luu'),
        ),
    ]
