# Generated by Django 4.2.16 on 2026-06-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_team_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen_reviews_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần cuối xem đánh giá'),
        ),
    ]
